name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 같은 브랜치의 이전 워크플로는 취소
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 변경 파일에 따라 어떤 잡을 돌릴지 결정
  changes:
    runs-on: ubuntu-latest
    outputs:
      unit: ${{ steps.filter.outputs.unit }}
      e2e: ${{ steps.filter.outputs.e2e }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            unit:
              - 'src/**'
              - 'package.json'
              - 'pnpm-lock.yaml'
              - 'tsconfig.json'
              - 'vitest.config.ts'
              - 'vitest.setup.ts'
            e2e:
              - 'src/**'
              - 'tests/e2e/**'
              - 'playwright.config.ts'
              - 'package.json'
              - 'pnpm-lock.yaml'

  unit:
    needs: changes
    if: needs.changes.outputs.unit == 'true' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - name: Lint
        run: pnpm lint
      - name: Type check & Build
        run: pnpm build
      - name: Unit tests (Vitest)
        run: pnpm test

  e2e:
    needs: changes
    if: needs.changes.outputs.e2e == 'true' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - name: Install Playwright browsers
        run: pnpm dlx playwright install --with-deps
      - name: E2E tests (Playwright)
        run: pnpm test:e2e
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results
          retention-days: 7
